Login_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
]

authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'
urlpatterns = [
		path('', views.home, name='home'),
		path('signup/', views.signup, name='signup'),
		path('signin/', views.signin, name='signin'),
		path('signout/', views.logout, name='logout'),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages


# Create your views here.

def home(request):
    if request.method == "POST":
        username = request.POST['username']
        fisrtname = request.POST['fisrtname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password = request.POST['password']
        password1 = request.POST['password1']

        myuser = User.objects.create_user(username, email, password)
        myuser.first_name = fisrtname
        myuser.last_name = lastname

        myuser.save()

        messages.success(request,'Your Account has been successfully created')

        return redirect('signin')
    return render(request, 'authentication/index.html')


def signup(request):
    return render(request, 'authentication/signup.html')


def signin(request):
    return render(request, 'authentication/signin.html')


def logout(request):
    return render(request, 'authentication/logout.html')

templates/authentication/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authentication</title>
</head>
<body>

    <h3>Welcome to Django</h3>

    <button type="submit"> <a href="/signup">SignUp</a> </button>
    <button type="submit"> <a href="/signin">SignIn</a> </button>
    <button type="submit"> <a href="/logout">LogOut</a> </button>

</body>
</html>

templates/authentication/logout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Logout</title>
</head>
<body>

</body>
</html>

templates/authentication/signin.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Sign In</title>
    </head>
    <body>
        <h3>Sign In</h3>
{#        <form action="/signup" method="post">#}
{#            {% csrf_token %}#}
{#            <label for="username">User Name</label>#}
{#            <input type="text" id="username" name="username" placeholder="Create a username (only letters and numbers)" required>#}
{#            <br>#}
{#            <label for="firstname">First Name</label>#}
{#            <input type="text" id="firstname" name="firstname" placeholder="Enter Your First Name" required>#}
{#            <br>#}
{#            <label for="lastname">Last Name</label>#}
{#            <input type="text" id="lastname" name="lastname" placeholder="Enter Your Last Name" required>#}
{#            <br>#}
{#            <label for="email">Email Address</label>#}
{#            <input type="email" id="email" name="email" placeholder="Enter Your Email Address" required>#}
{#            <br>#}
{#            <label for="password">Password</label>#}
{#            <input type="password" id="password" name="password" placeholder="Create a Password" required>#}
{#            <br>#}
{#            <label for="password1">Confirm Your Password</label>#}
{#            <input type="password" id="password1" name="password1" placeholder="Confirm Your Password" required>#}
{#            <br>#}
{#            <button type="submit">Sign Up</button>#}
{#        </form>#}
    </body>
</html>

templates/authentication/signup.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Sign Up</title>
    </head>
    <body>
        <h3>Sign Up</h3>
        <form action="{% url 'authentication:signin' %}" method="post">
{#        <form action="/signin" method="post">#}
            {% csrf_token %}
            <label for="username">User Name</label>
            <input type="text" id="username" name="username" placeholder="Create a username (only letters and numbers)" required>
            <br>
            <label for="firstname">First Name</label>
            <input type="text" id="firstname" name="firstname" placeholder="Enter Your First Name" required>
            <br>
            <label for="lastname">Last Name</label>
            <input type="text" id="lastname" name="lastname" placeholder="Enter Your Last Name" required>
            <br>
            <label for="email">Email Address</label>
            <input type="email" id="email" name="email" placeholder="Enter Your Email Address" required>
            <br>
            <label for="password">Password</label>
            <input type="password" id="password" name="password" placeholder="Create a Password" required>
            <br>
            <label for="password1">Confirm Your Password</label>
            <input type="password" id="password1" name="password1" placeholder="Confirm Your Password" required>
            <br>
            <button type="submit">Sign Up</button>
        </form>
    </body>
</html>